### ISSUE TITLE
Kubernetes Operator - resolve protocol missing on hostname

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/galasa-kubernetes-operator#14]
Several components require a protocol inside the opterator which it bases from the k8s hostname. Need to add check and fill in missing protocol on those components

**Comment by techcobweb** [comment]
@Jimbo4794 How do yo mean a protocol ? Do you have any examples of what's needed and where ?

**Comment by techcobweb** [comment]
Given our recent decision to not persue the kube operator in its' current form, can this issue be closed @Jimbo4794 ?

**Comment by techcobweb** [comment]
Assuming we can close this. Please re-open if required.
